version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: simpleshop_db
    restart: always
    environment:
      POSTGRES_USER: simpleshop
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: simpleshop_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: